name: Frontend Security & Env Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  frontend-checks:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install frontend dependencies
      - name: Install Frontend Dependencies
        run: |
          cd forumly_frontend
          npm ci

      # 4. Run frontend security check
      - name: Frontend Security Check
        run: |
          cd forumly_frontend
          npm audit --audit-level=moderate

      # 5. Run frontend environment check using clienvy
      - name: Frontend Env Check
        run: |
          cd forumly_frontend
          npx clienvy check
